package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/fatih/color"
	"github.com/kern-dev/kern-agent/internal/config"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Inject KERN shell hooks into your shell configuration",
	Long: `Detects your current shell (zsh, bash, or fish) and appends
KERN hook functions to the appropriate config file.

After running this command, restart your shell or source the config file.`,
	RunE: runInit,
}

var forceShell string

func init() {
	initCmd.Flags().StringVar(&forceShell, "shell", "", "Force a specific shell (zsh, bash, fish)")
}

// zshHook is appended to ~/.zshrc
const zshHook = `
# ── KERN terminal hooks ──────────────────────────────────────────────────────
if command -v kern &>/dev/null; then
  kern_preexec() {
    export KERN_CMD_START=$(date +%%s%%N 2>/dev/null || python3 -c "import time; print(int(time.time()*1e9))")
    export KERN_PREV_CMD="$1"
  }
  kern_precmd() {
    local _exit=$?
    if [[ -n "$KERN_PREV_CMD" ]]; then
      kern record \
        --cmd "$KERN_PREV_CMD" \
        --start "${KERN_CMD_START:-0}" \
        --exit "$_exit" \
        --cwd "$PWD" \
        &>/dev/null &!
      unset KERN_PREV_CMD KERN_CMD_START
    fi
  }
  autoload -Uz add-zsh-hook 2>/dev/null
  add-zsh-hook preexec kern_preexec
  add-zsh-hook precmd kern_precmd
fi
# ── end KERN ─────────────────────────────────────────────────────────────────
`

// bashHook is appended to ~/.bashrc
const bashHook = `
# ── KERN terminal hooks ──────────────────────────────────────────────────────
if command -v kern &>/dev/null; then
  __kern_preexec() {
    [[ "$BASH_COMMAND" == "$PROMPT_COMMAND" ]] && return
    export KERN_CMD_START=$(date +%%s%%N 2>/dev/null || python3 -c "import time; print(int(time.time()*1e9))")
    export KERN_PREV_CMD="$BASH_COMMAND"
  }
  __kern_precmd() {
    local _exit=$?
    if [[ -n "$KERN_PREV_CMD" ]]; then
      kern record \
        --cmd "$KERN_PREV_CMD" \
        --start "${KERN_CMD_START:-0}" \
        --exit "$_exit" \
        --cwd "$PWD" \
        &>/dev/null &
      unset KERN_PREV_CMD KERN_CMD_START
    fi
  }
  trap '__kern_preexec' DEBUG
  PROMPT_COMMAND="__kern_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
fi
# ── end KERN ─────────────────────────────────────────────────────────────────
`

// fishHook is written to ~/.config/fish/conf.d/kern.fish
const fishHook = `# KERN terminal hooks — auto-generated by kern init
if command -v kern > /dev/null 2>&1
  function __kern_preexec --on-event fish_preexec
    set -gx KERN_CMD_START (date +%%s%%N 2>/dev/null; or python3 -c "import time; print(int(time.time()*1e9))")
    set -gx KERN_PREV_CMD $argv[1]
  end

  function __kern_postexec --on-event fish_postexec
    set -l _exit $status
    if set -q KERN_PREV_CMD
      kern record \
        --cmd "$KERN_PREV_CMD" \
        --start "$KERN_CMD_START" \
        --exit "$_exit" \
        --cwd "$PWD" \
        &>/dev/null &
      set -e KERN_PREV_CMD
      set -e KERN_CMD_START
    end
  end
end
`

// dashboardURL derives the web dashboard URL from the configured API endpoint.
// e.g. "https://kern.dev/api" → "https://kern.dev"
//      "https://kern.dev/api/" → "https://kern.dev"
//      "https://kern.dev"      → "https://kern.dev"
func dashboardURL(apiEndpoint string) string {
	u := strings.TrimRight(apiEndpoint, "/")
	if strings.HasSuffix(u, "/api") {
		return strings.TrimSuffix(u, "/api")
	}
	return u
}

// termLink returns an ANSI OSC 8 hyperlink that renders as a clickable link
// in terminals that support it (iTerm2, Warp, GNOME Terminal, Windows Terminal, etc.)
func termLink(text, url string) string {
	return fmt.Sprintf("\033]8;;%s\033\\%s\033]8;;\033\\", url, text)
}

// openBrowser launches the user's default browser to the given URL.
// It fires-and-forgets: errors are silently ignored so init never fails
// just because xdg-open isn't installed.
func openBrowser(url string) {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", url)
	case "windows":
		cmd = exec.Command("cmd", "/c", "start", url)
	default:
		// Linux and everything else
		cmd = exec.Command("xdg-open", url)
	}
	// Detach fully — we don't care about the exit code
	_ = cmd.Start()
}

func runInit(cmd *cobra.Command, args []string) error {
	shell := forceShell
	if shell == "" {
		shell = detectShell()
	}

	bold := color.New(color.Bold)
	green := color.New(color.FgGreen)
	cyan := color.New(color.FgCyan)
	dim := color.New(color.Faint)

	bold.Printf("\n  KERN_ shell hook installer\n\n")
	fmt.Printf("  Detected shell: %s\n\n", cyan.Sprint(shell))

	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot find home directory: %w", err)
	}

	var sourceCmd string

	switch shell {
	case "zsh":
		target := filepath.Join(home, ".zshrc")
		if err := appendIfMissing(target, zshHook, "KERN terminal hooks"); err != nil {
			return err
		}
		green.Printf("  ✓  Shell hook added to %s\n", target)
		sourceCmd = "source ~/.zshrc"

	case "bash":
		target := filepath.Join(home, ".bashrc")
		if err := appendIfMissing(target, bashHook, "KERN terminal hooks"); err != nil {
			return err
		}
		green.Printf("  ✓  Shell hook added to %s\n", target)
		sourceCmd = "source ~/.bashrc"

	case "fish":
		dir := filepath.Join(home, ".config", "fish", "conf.d")
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		target := filepath.Join(dir, "kern.fish")
		if err := os.WriteFile(target, []byte(fishHook), 0644); err != nil {
			return err
		}
		green.Printf("  ✓  Hook file written to %s\n", target)
		sourceCmd = "exec fish"

	default:
		return fmt.Errorf("unsupported shell %q — use --shell to specify zsh, bash, or fish", shell)
	}

	// ── Load config and derive dashboard URL ───────────────────────────────
	cfg, _ := config.Load()
	dashURL := dashboardURL(cfg.APIEndpoint)

	configured := cfg.APIEndpoint != "" && cfg.APIEndpoint != config.DefaultConfig().APIEndpoint

	fmt.Println()
	green.Println("  ✓  Local buffer initialized at ~/.kern/events.db")
	fmt.Println()

	// ── Dashboard section ──────────────────────────────────────────────────
	bold.Println("  ─────────────────────────────────────────────")
	bold.Println("  Your KERN Dashboard")
	bold.Println("  ─────────────────────────────────────────────")
	fmt.Println()

	if configured {
		// Show clickable hyperlink (OSC 8 — works in iTerm2, Warp, GNOME Terminal, Windows Terminal)
		link := termLink(dashURL, dashURL)
		fmt.Printf("  %s  %s\n", green.Sprint("→"), link)
		fmt.Println()
		fmt.Printf("  %s\n", dim.Sprint("Opening in your browser…"))
		fmt.Println()

		// Small pause so the output is readable before the browser pops
		time.Sleep(400 * time.Millisecond)
		openBrowser(dashURL)
	} else {
		// API endpoint hasn't been configured yet — guide them
		fmt.Printf("  %s %s\n",
			dim.Sprint("Dashboard URL:"),
			cyan.Sprint(dashURL),
		)
		fmt.Println()
		fmt.Printf("  %s Configure your endpoint and API key to activate:\n\n", dim.Sprint("→"))
		fmt.Printf("    %s\n", cyan.Sprintf("kern config --endpoint https://your-kern-host/api --key YOUR_API_KEY"))
		fmt.Println()
		fmt.Printf("  %s Then run %s to open your dashboard.\n",
			dim.Sprint("→"),
			cyan.Sprint("kern dashboard"),
		)
	}

	fmt.Println()
	bold.Println("  ─────────────────────────────────────────────")
	fmt.Println()

	// ── Shell reload reminder ──────────────────────────────────────────────
	bold.Println("  KERN is now active.")
	fmt.Println("  Every command you run will be captured automatically.")
	fmt.Println()
	fmt.Printf("  Reload your shell:  %s\n", cyan.Sprint(sourceCmd))
	fmt.Printf("  Check buffer:       %s\n", cyan.Sprint("kern status"))
	fmt.Printf("  Sync now:           %s\n", cyan.Sprint("kern sync"))
	fmt.Println()

	return nil
}

func detectShell() string {
	shell := os.Getenv("SHELL")
	base := filepath.Base(shell)
	switch base {
	case "zsh", "bash", "fish":
		return base
	}
	return "bash"
}

func appendIfMissing(path, content, marker string) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if strings.Contains(string(existing), marker) {
		fmt.Printf("  (hooks already present in %s — skipping)\n", path)
		return nil
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(content)
	return err
}
