package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Inject KERN shell hooks into your shell configuration",
	Long: `Detects your current shell (zsh, bash, or fish) and appends
KERN hook functions to the appropriate config file.

After running this command, restart your shell or source the config file.`,
	RunE: runInit,
}

var forceShell string

func init() {
	initCmd.Flags().StringVar(&forceShell, "shell", "", "Force a specific shell (zsh, bash, fish)")
}

// zshHook is appended to ~/.zshrc
const zshHook = `
# ── KERN terminal hooks ──────────────────────────────────────────────────────
if command -v kern &>/dev/null; then
  kern_preexec() {
    export KERN_CMD_START=$(date +%%s%%N 2>/dev/null || python3 -c "import time; print(int(time.time()*1e9))")
    export KERN_PREV_CMD="$1"
  }
  kern_precmd() {
    local _exit=$?
    if [[ -n "$KERN_PREV_CMD" ]]; then
      kern record \
        --cmd "$KERN_PREV_CMD" \
        --start "${KERN_CMD_START:-0}" \
        --exit "$_exit" \
        --cwd "$PWD" \
        &>/dev/null &!
      unset KERN_PREV_CMD KERN_CMD_START
    fi
  }
  autoload -Uz add-zsh-hook 2>/dev/null
  add-zsh-hook preexec kern_preexec
  add-zsh-hook precmd kern_precmd
fi
# ── end KERN ─────────────────────────────────────────────────────────────────
`

// bashHook is appended to ~/.bashrc
const bashHook = `
# ── KERN terminal hooks ──────────────────────────────────────────────────────
if command -v kern &>/dev/null; then
  __kern_preexec() {
    [[ "$BASH_COMMAND" == "$PROMPT_COMMAND" ]] && return
    export KERN_CMD_START=$(date +%%s%%N 2>/dev/null || python3 -c "import time; print(int(time.time()*1e9))")
    export KERN_PREV_CMD="$BASH_COMMAND"
  }
  __kern_precmd() {
    local _exit=$?
    if [[ -n "$KERN_PREV_CMD" ]]; then
      kern record \
        --cmd "$KERN_PREV_CMD" \
        --start "${KERN_CMD_START:-0}" \
        --exit "$_exit" \
        --cwd "$PWD" \
        &>/dev/null &
      unset KERN_PREV_CMD KERN_CMD_START
    fi
  }
  trap '__kern_preexec' DEBUG
  PROMPT_COMMAND="__kern_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
fi
# ── end KERN ─────────────────────────────────────────────────────────────────
`

// fishHook is written to ~/.config/fish/conf.d/kern.fish
const fishHook = `# KERN terminal hooks — auto-generated by kern init
if command -v kern > /dev/null 2>&1
  function __kern_preexec --on-event fish_preexec
    set -gx KERN_CMD_START (date +%%s%%N 2>/dev/null; or python3 -c "import time; print(int(time.time()*1e9))")
    set -gx KERN_PREV_CMD $argv[1]
  end

  function __kern_postexec --on-event fish_postexec
    set -l _exit $status
    if set -q KERN_PREV_CMD
      kern record \
        --cmd "$KERN_PREV_CMD" \
        --start "$KERN_CMD_START" \
        --exit "$_exit" \
        --cwd "$PWD" \
        &>/dev/null &
      set -e KERN_PREV_CMD
      set -e KERN_CMD_START
    end
  end
end
`

func runInit(cmd *cobra.Command, args []string) error {
	shell := forceShell
	if shell == "" {
		shell = detectShell()
	}

	bold := color.New(color.Bold)
	green := color.New(color.FgGreen)
	cyan := color.New(color.FgCyan)

	bold.Printf("\n  KERN_ shell hook installer\n\n")
	fmt.Printf("  Detected shell: %s\n\n", cyan.Sprint(shell))

	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot find home directory: %w", err)
	}

	switch shell {
	case "zsh":
		target := filepath.Join(home, ".zshrc")
		if err := appendIfMissing(target, zshHook, "KERN terminal hooks"); err != nil {
			return err
		}
		green.Printf("  ✓ Hooks added to %s\n", target)
		fmt.Printf("  Run: %s\n\n", cyan.Sprint("source ~/.zshrc"))

	case "bash":
		target := filepath.Join(home, ".bashrc")
		if err := appendIfMissing(target, bashHook, "KERN terminal hooks"); err != nil {
			return err
		}
		green.Printf("  ✓ Hooks added to %s\n", target)
		fmt.Printf("  Run: %s\n\n", cyan.Sprint("source ~/.bashrc"))

	case "fish":
		dir := filepath.Join(home, ".config", "fish", "conf.d")
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		target := filepath.Join(dir, "kern.fish")
		if err := os.WriteFile(target, []byte(fishHook), 0644); err != nil {
			return err
		}
		green.Printf("  ✓ Hook file written to %s\n", target)
		fmt.Printf("  Run: %s\n\n", cyan.Sprint("exec fish"))

	default:
		return fmt.Errorf("unsupported shell %q — use --shell to specify zsh, bash, or fish", shell)
	}

	bold.Println("  KERN is now active. Every command you run will be captured.")
	fmt.Println("  Run `kern status` to see your local buffer.")
	fmt.Println()
	return nil
}

func detectShell() string {
	shell := os.Getenv("SHELL")
	base := filepath.Base(shell)
	switch base {
	case "zsh", "bash", "fish":
		return base
	}
	return "bash"
}

func appendIfMissing(path, content, marker string) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if strings.Contains(string(existing), marker) {
		fmt.Printf("  (hooks already present in %s — skipping)\n", path)
		return nil
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(content)
	return err
}
